import { readFile, readdir, writeFile, rename } from 'node:fs/promises';
import { join, resolve } from 'node:path';

const DEFAULT_TIMEOUT_MS = 8_000;
const DEFAULT_CONTEXT_CHARS = 12_000;
const rawUrl = String(process.env.NOCTURNE_API_URL || '').trim();
const token = String(process.env.NOCTURNE_API_TOKEN || '').trim();
const timeoutMs = positiveInt(process.env.NOCTURNE_TIMEOUT_MS, DEFAULT_TIMEOUT_MS);
const contextChars = positiveInt(process.env.NOCTURNE_CONTEXT_CHARS, DEFAULT_CONTEXT_CHARS);
const recallLimit = positiveInt(process.env.NOCTURNE_RECALL_LIMIT, 8);

function positiveInt(value, fallback) { const parsed=Number.parseInt(value,10); return Number.isFinite(parsed)&&parsed>0?parsed:fallback; }
function resolveApiUrl(value){if(!value)return null;try{const url=new URL(value);url.pathname=url.pathname.replace(/\/(?:mcp)?\/?$/,'');return url}catch(error){console.error('Invalid NOCTURNE_API_URL:',error.message);return null}}
const apiUrl=resolveApiUrl(rawUrl);
function endpoint(pathname){const url=new URL(apiUrl);url.pathname=`${url.pathname.replace(/\/$/,'')}${pathname}`;return url}
async function post(pathname,body){const started=Date.now();const response=await fetch(endpoint(pathname),{method:'POST',headers:{'content-type':'application/json',accept:'application/json',...(token?{authorization:`Bearer ${token}`}:{})},body:JSON.stringify(body),signal:AbortSignal.timeout(timeoutMs)});const raw=await response.text();console.log('[nocturne-http]',JSON.stringify({path:pathname,status:response.status,ok:response.ok,ms:Date.now()-started,responseChars:raw.length}));if(!response.ok)throw new Error(`Nocturne direct API returned ${response.status}: ${raw.slice(0,500)}`);if(!raw.trim())return{};try{return JSON.parse(raw)}catch{throw new Error(`Nocturne direct API returned invalid JSON: ${raw.slice(0,300)}`)}}
export const nocturneConfigured=Boolean(apiUrl&&token);
export const nocturneMode='direct-http';
function compactEventText(value,limit=240){return String(value||'').replace(/^#+\s*/gm,'').replace(/【[^】]+】/g,'').replace(/\s+/g,' ').trim().slice(0,limit)}
function memoryText(item){if(typeof item==='string')return item.trim();if(!item||typeof item!=='object')return'';return String(item.content??item.text??item.memory??item.summary??item.value??'').trim()}
function collectMemoryItems(root){for(const key of ['memories','results','related','items','matches','documents'])if(Array.isArray(root?.[key]))return root[key];return[]}
function normalizeRecall(payload){const root=payload?.data&&typeof payload.data==='object'?payload.data:payload||{};const core=memoryText(root.core??root.coreMemory??root.core_memory);const list=collectMemoryItems(root);const related=list.map(memoryText).filter(Boolean).join('\n\n')||(typeof root.related==='string'?root.related.trim():'');const suppliedContext=String(root.context??root.memoryContext??root.memory_context??root.prompt??'').trim();const sections=[];if(core)sections.push(`【核心记忆】\n${core}`);if(related)sections.push(`【与当前消息相关的记忆】\n${related}`);if(!sections.length&&suppliedContext)sections.push(suppliedContext);return{context:sections.join('\n\n').slice(0,contextChars),surfaced:compactEventText(root.surfaced??root.surfacedMemory??root.surfaced_memory??(list.length?memoryText(list[0]):'')),matches:list.length}}
export async function recallMemory(query){if(!apiUrl)return{context:'',surfaced:'',matches:0};const q=String(query||'').slice(0,800);const payload=await post('/api/integrations/nook/recall',{query:q,limit:recallLimit,contextChars});const normalized=normalizeRecall(payload);console.log('[nocturne-recall]',JSON.stringify({query:q.slice(0,80),matches:normalized.matches,contextChars:normalized.context.length,surfacedChars:normalized.surfaced.length,responseKeys:Object.keys(payload||{}).slice(0,16)}));return normalized}
export async function storeMemory({message='',reply='',summary='',content='',kind='memory',importance=5,tags='nook,dialogue,auto'}){if(!apiUrl)throw new Error('NOCTURNE_NOT_CONFIGURED');const normalizedSummary=String(summary||'').trim(),normalizedContent=String(content||'').trim();if(!normalizedSummary&&!normalizedContent)throw new Error('EMPTY_MEMORY_CONTENT');const memoryContent=normalizedContent||`长期记忆摘要：${normalizedSummary}\n\n来源对话：\n言言：${message}\n沈屿：${reply}`;const validKinds=new Set(['memory','feel','writing','unresolved','window']);const payload=await post('/api/integrations/nook/memories',{content:memoryContent.slice(0,3500),kind:validKinds.has(kind)?kind:'memory',tags,importance:Math.max(1,Math.min(10,Number(importance)||5)),source:'nook'});const receipt=String(payload?.message||payload?.id||payload?.data?.id||payload?.data?.message||'').trim();if(!receipt)throw new Error(`NOCTURNE_STORE_UNCONFIRMED keys=${Object.keys(payload||{}).join(',')}`);console.log('[nocturne-store]',JSON.stringify({confirmed:true,receipt:receipt.slice(0,100),contentChars:memoryContent.length,kind}));return receipt}

// Older builds could advance memoryCompressedUpTo without a durable local archive receipt.
// On boot, reconcile the cursor from actual successful archive receipts. This makes the
// next reply retry every missing 20-message window instead of silently skipping it.
const reconcileCompressionCursors=async()=>{const dataDir=resolve(process.env.GATEWAY_DATA_DIR||'/tmp/nook-gateway'),dir=join(dataDir,'conversations');let names=[];try{names=await readdir(dir)}catch(error){console.warn('[memory-reconcile] conversations unavailable:',error?.message||error);return}for(const name of names.filter(n=>n.endsWith('.json'))){const path=join(dir,name);try{const conversation=JSON.parse(await readFile(path,'utf8'));const archives=Array.isArray(conversation.memoryArchives)?conversation.memoryArchives:[];const valid=archives.filter(a=>Number(a?.count)===20&&Number(a?.start)>0&&Number(a?.end)===Number(a?.start)+19&&String(a?.content||a?.summary||'').trim());let cursor=0;for(;;){const next=valid.find(a=>Number(a.start)===cursor+1&&Number(a.end)===cursor+20);if(!next)break;cursor+=20}const old=Math.max(0,Number(conversation.memoryCompressedUpTo)||0);if(old!==cursor){conversation.memoryCompressedUpTo=cursor;conversation.updatedAt=Date.now();const tmp=`${path}.${process.pid}.${Date.now()}.reconcile.tmp`;await writeFile(tmp,JSON.stringify(conversation),'utf8');await rename(tmp,path);console.warn('[memory-reconcile]',JSON.stringify({conversationId:conversation.id,oldCursor:old,reconciledCursor:cursor,archiveReceipts:valid.length}))}else console.log('[memory-reconcile]',JSON.stringify({conversationId:conversation.id,cursor,archiveReceipts:valid.length}))}catch(error){console.error('[memory-reconcile] failed',name,error?.message||error)}}};
setTimeout(()=>reconcileCompressionCursors().catch(error=>console.error('[memory-reconcile] fatal:',error)),1200).unref?.();
