import { readFile, readdir, writeFile, rename } from 'node:fs/promises';
import { join, resolve } from 'node:path';

const DEFAULT_TIMEOUT_MS=8000,DEFAULT_CONTEXT_CHARS=12000;
const rawUrl=String(process.env.NOCTURNE_API_URL||'').trim(),token=String(process.env.NOCTURNE_API_TOKEN||'').trim();
const positiveInt=(v,f)=>{const n=Number.parseInt(v,10);return Number.isFinite(n)&&n>0?n:f},timeoutMs=positiveInt(process.env.NOCTURNE_TIMEOUT_MS,DEFAULT_TIMEOUT_MS),contextChars=positiveInt(process.env.NOCTURNE_CONTEXT_CHARS,DEFAULT_CONTEXT_CHARS),recallLimit=positiveInt(process.env.NOCTURNE_RECALL_LIMIT,8);
function resolveApiUrl(value){if(!value)return null;try{const url=new URL(value);url.pathname=url.pathname.replace(/\/(?:mcp)?\/?$/,'');return url}catch(error){console.error('Invalid NOCTURNE_API_URL:',error.message);return null}}
const apiUrl=resolveApiUrl(rawUrl);function endpoint(pathname){const url=new URL(apiUrl);url.pathname=`${url.pathname.replace(/\/$/,'')}${pathname}`;return url}
async function post(pathname,body){const started=Date.now(),response=await fetch(endpoint(pathname),{method:'POST',headers:{'content-type':'application/json',accept:'application/json',...(token?{authorization:`Bearer ${token}`}:{})},body:JSON.stringify(body),signal:AbortSignal.timeout(timeoutMs)}),raw=await response.text();console.log('[nocturne-http]',JSON.stringify({path:pathname,status:response.status,ok:response.ok,ms:Date.now()-started,responseChars:raw.length}));if(!response.ok)throw new Error(`Nocturne direct API returned ${response.status}: ${raw.slice(0,500)}`);if(!raw.trim())return{};try{return JSON.parse(raw)}catch{throw new Error(`Nocturne direct API returned invalid JSON: ${raw.slice(0,300)}`)}}
export const nocturneConfigured=Boolean(apiUrl&&token),nocturneMode='direct-http';
function compactEventText(value,limit=240){return String(value||'').replace(/^#+\s*/gm,'').replace(/【[^】]+】/g,'').replace(/\s+/g,' ').trim().slice(0,limit)}
function memoryText(item){if(typeof item==='string')return item.trim();if(!item||typeof item!=='object')return'';for(const key of ['content','text','memory','summary','value','description','body']){const v=item[key];if(typeof v==='string'&&v.trim())return v.trim()}return''}
function deepMemoryItems(value,depth=0,seen=new Set()){if(depth>5||value==null)return[];if(typeof value==='string')return value.trim()?[value.trim()]:[];if(typeof value!=='object'||seen.has(value))return[];seen.add(value);if(Array.isArray(value))return value.flatMap(v=>deepMemoryItems(v,depth+1,seen));const direct=memoryText(value),out=direct?[direct]:[];for(const [key,v] of Object.entries(value)){if(['query','message','status','id','source','kind','tags'].includes(key))continue;if(['memories','results','related','items','matches','documents','records','hits','data','context','memoryContext','memory_context','core','coreMemory','core_memory'].includes(key))out.push(...deepMemoryItems(v,depth+1,seen))}return [...new Set(out)]}
function normalizeRecall(payload){const roots=[payload?.data,payload?.result,payload].filter(v=>v&&typeof v==='object');let supplied='',surfaced='';for(const root of roots){supplied=String(root.context??root.memoryContext??root.memory_context??root.prompt??'').trim()||supplied;surfaced=String(root.surfaced??root.surfacedMemory??root.surfaced_memory??'').trim()||surfaced}const list=deepMemoryItems(payload).filter(text=>text!==supplied);const context=(supplied||list.join('\n\n')).slice(0,contextChars);return{context,surfaced:compactEventText(surfaced||list[0]||''),matches:list.length}}
export async function recallMemory(query){if(!apiUrl)return{context:'',surfaced:'',matches:0};const q=String(query||'').slice(0,800),payload=await post('/api/integrations/nook/recall',{query:q,limit:recallLimit,contextChars}),normalized=normalizeRecall(payload);console.log('[nocturne-recall]',JSON.stringify({query:q.slice(0,80),matches:normalized.matches,contextChars:normalized.context.length,surfacedChars:normalized.surfaced.length,responseKeys:Object.keys(payload||{}).slice(0,16)}));return normalized}
export async function storeMemory({message='',reply='',summary='',content='',kind='memory',importance=5,tags='nook,dialogue,auto'}){if(!apiUrl)throw new Error('NOCTURNE_NOT_CONFIGURED');const normalizedSummary=String(summary||'').trim(),normalizedContent=String(content||'').trim();if(!normalizedSummary&&!normalizedContent)throw new Error('EMPTY_MEMORY_CONTENT');const memoryContent=normalizedContent||`长期记忆摘要：${normalizedSummary}\n\n来源对话：\n言言：${message}\n沈屿：${reply}`,validKinds=new Set(['memory','feel','writing','unresolved','window']),payload=await post('/api/integrations/nook/memories',{content:memoryContent.slice(0,3500),kind:validKinds.has(kind)?kind:'memory',tags,importance:Math.max(1,Math.min(10,Number(importance)||5)),source:'nook'}),receipt=String(payload?.message||payload?.id||payload?.data?.id||payload?.data?.message||'').trim();if(!receipt)throw new Error(`NOCTURNE_STORE_UNCONFIRMED keys=${Object.keys(payload||{}).join(',')}`);console.log('[nocturne-store]',JSON.stringify({confirmed:true,receipt:receipt.slice(0,100),contentChars:memoryContent.length,kind}));return receipt}
const reconcileCompressionCursors=async()=>{const dataDir=resolve(process.env.GATEWAY_DATA_DIR||'/tmp/nook-gateway'),dir=join(dataDir,'conversations');let names=[];try{names=await readdir(dir)}catch(error){console.warn('[memory-reconcile] conversations unavailable:',error?.message||error);return}for(const name of names.filter(n=>n.endsWith('.json'))){const path=join(dir,name);try{const conversation=JSON.parse(await readFile(path,'utf8')),archives=Array.isArray(conversation.memoryArchives)?conversation.memoryArchives:[],valid=archives.filter(a=>Number(a?.count)===20&&Number(a?.start)>0&&Number(a?.end)===Number(a?.start)+19&&String(a?.content||a?.summary||'').trim());let cursor=0;for(;;){const next=valid.find(a=>Number(a.start)===cursor+1&&Number(a.end)===cursor+20);if(!next)break;cursor+=20}const old=Math.max(0,Number(conversation.memoryCompressedUpTo)||0);if(old!==cursor){conversation.memoryCompressedUpTo=cursor;conversation.updatedAt=Date.now();const tmp=`${path}.${process.pid}.${Date.now()}.reconcile.tmp`;await writeFile(tmp,JSON.stringify(conversation),'utf8');await rename(tmp,path);console.warn('[memory-reconcile]',JSON.stringify({conversationId:conversation.id,oldCursor:old,reconciledCursor:cursor,archiveReceipts:valid.length}))}else console.log('[memory-reconcile]',JSON.stringify({conversationId:conversation.id,cursor,archiveReceipts:valid.length}))}catch(error){console.error('[memory-reconcile] failed',name,error?.message||error)}}};
setTimeout(()=>reconcileCompressionCursors().catch(error=>console.error('[memory-reconcile] fatal:',error)),1200).unref?.();
