import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here=dirname(fileURLToPath(import.meta.url));
const sourcePath=join(here,'server.mjs');
const runtimePath=join(here,'.server-runtime.mjs');
let source=await readFile(sourcePath,'utf8');
source=source.replace('contextWindowMessages=20,memoryBatchMessages=20','contextWindowMessages=20,memoryBatchMessages=40');
source=source.replaceAll('compressed-20,auto','compressed-20-rounds,auto');

const marker="if(['/api/uploads','/api/upload','/api/images'].includes(url.pathname))",getMarker="const conversationMatch=url.pathname.match(/^\\/api\\/conversations";
const manual=`if(url.pathname==='/api/memory/compress-now'){const body=await readJson(req),conversationId=resolveConversationId(body?.conversationId);if(!conversationId)return sendJson(res,400,{error:'Invalid conversation'},origin);if(!nocturneConfigured)return sendJson(res,503,{error:'Memory service not configured'},origin);const config=await loadMemoryModelConfig();if(!publicMemoryModelConfig(config).configured)return sendJson(res,503,{error:'Memory compression model not configured'},origin);const conversation=await loadConversation(conversationId),history=conversation.messages.filter(entry=>['user','assistant'].includes(entry.role));const complete=[];for(let i=0;i<history.length-1;i++){if(history[i]?.role==='user'&&history[i+1]?.role==='assistant'){complete.push(history[i],history[i+1]);i++}}const batch=complete.slice(-10);if(!batch.length)return sendJson(res,200,{ok:true,count:0,items:[],message:'还没有完整对话可压缩'},origin);const transcript=batch.map((entry,index)=>\`${'${index+1}'}. ${'${entry.role===\'user\'?\'言言\':\'沈屿\'}'}：${'${memoryTextForEntry(entry)||\'[无文字内容]\'}'}\`).join('\\n'),prompt=\`下面是最近 ${'${Math.floor(batch.length/2)}'} 轮对话。请把其中真正值得长期保留的信息压缩成一条简洁、完整、可检索的长期记忆。只保留重要事实、偏好、决定、关系变化、情绪事件、项目进展或重要结论；合并重复，不添加原文没有的信息。不要列多条，不要编号。严格输出 JSON：{"memories":["唯一的一条记忆"]}。\\n\\n${'${transcript}'}\`,result=await runMemoryCompressionModel({config,systemPrompt:'你是 Nook 独立的长期记忆压缩器。手动测试时必须把最近对话合并成且只输出一条长期记忆。',prompt}),parsed=parseMemoryItems(result.text),item=parsed.filter(Boolean).join('；').trim();if(!item)throw new Error('EMPTY_MEMORY_SUMMARY');await storeMemory({content:item,kind:'window',importance:6,tags:'nook,dialogue,manual-test,last-5-rounds,single'});conversation.memoryArchives.push({id:crypto.randomUUID(),start:null,end:null,count:batch.length,rounds:Math.floor(batch.length/2),items:[item],model:result.model,manual:true,createdAt:Date.now(),afterMessageId:batch.at(-1)?.id||''});await saveConversation(conversation);return sendJson(res,200,{ok:true,count:1,rounds:Math.floor(batch.length/2),items:[item],model:result.model,message:'近5轮已压缩为1条记忆'},origin)};`;
source=source.replace("const loadMemoryModelConfig=()=>readJsonFile(memoryModelConfigPath,{}),saveMemoryModelConfig=config=>writeJsonAtomic(memoryModelConfigPath,normalizeMemoryModelConfig(config));",`const loadMemoryModelConfig=()=>readJsonFile(memoryModelConfigPath,{}),saveMemoryModelConfig=config=>writeJsonAtomic(memoryModelConfigPath,normalizeMemoryModelConfig(config));const minimaxTtsConfigPath=join(dataDir,'minimax-tts.json'),loadMinimaxTtsConfig=()=>readJsonFile(minimaxTtsConfigPath,{}),publicMinimaxTtsConfig=config=>({configured:Boolean(config?.key&&config?.voiceId),voiceId:String(config?.voiceId||''),model:String(config?.model||'speech-2.8-hd'),hasKey:Boolean(config?.key)});`);
const ttsGet=`if(req.method==='GET'&&url.pathname==='/api/settings/minimax'){return sendJson(res,200,publicMinimaxTtsConfig(await loadMinimaxTtsConfig()),origin)}`;source=source.replace(getMarker,ttsGet+getMarker);
const tts=`if(url.pathname==='/api/settings/minimax'){const body=await readJson(req),previous=await loadMinimaxTtsConfig(),key=typeof body?.key==='string'&&body.key.trim()?body.key.trim():String(previous?.key||''),voiceId=String(body?.voiceId||'').trim(),model=String(body?.model||'speech-2.8-hd').trim();if(!key||!voiceId)return sendJson(res,400,{error:'API Key 和 Voice ID 都需要填写'},origin);const config={key,voiceId,model};await writeJsonAtomic(minimaxTtsConfigPath,config);return sendJson(res,200,{ok:true,...publicMinimaxTtsConfig(config)},origin)}if(url.pathname==='/api/tts/minimax'){const body=await readJson(req),text=typeof body?.text==='string'?body.text.trim():'';if(!text)return sendJson(res,400,{error:'Text required'},origin);if(text.length>5000)return sendJson(res,400,{error:'Text must be at most 5000 characters'},origin);const config=await loadMinimaxTtsConfig(),apiKey=String(config?.key||'').trim(),voiceId=String(config?.voiceId||'').trim(),model=String(config?.model||'speech-2.8-hd').trim();if(!apiKey||!voiceId)return sendJson(res,503,{error:'MiniMax TTS not configured'},origin);const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),90000);try{const response=await fetch('https://api.minimax.cn/v1/t2a_v2',{method:'POST',headers:{Authorization:\`Bearer ${'${apiKey}'}\`,'Content-Type':'application/json'},body:JSON.stringify({model,text,stream:false,voice_setting:{voice_id:voiceId,speed:1,vol:1,pitch:0},audio_setting:{sample_rate:32000,bitrate:128000,format:'mp3',channel:1}}),signal:controller.signal}),result=await response.json().catch(()=>({}));if(!response.ok||result?.base_resp?.status_code!==0)return sendJson(res,502,{error:'MiniMax TTS failed',detail:result?.base_resp?.status_msg||\`HTTP ${'${response.status}'}\`},origin);const audio=result?.data?.audio;if(!audio)return sendJson(res,502,{error:'MiniMax returned no audio'},origin);const bytes=Buffer.from(audio,'hex'),headers={'content-type':'audio/mpeg','content-length':bytes.length,'cache-control':'private, no-store'};if(origin&&allowedOrigins.has(origin))headers['access-control-allow-origin']=origin;res.writeHead(200,headers);return res.end(bytes)}finally{clearTimeout(timeout)}};`;
source=source.replace(marker,manual+tts+marker);
// Preserve the model's autonomous voice choice as part of the assistant message. Audio is synthesized on playback from this exact text.
source=source.replace("if(!payload.reply)throw new Error('Model returned no visible reply');const assistantMessage={id:crypto.randomUUID(),requestId:requestId||undefined,role:'assistant',text:payload.reply,thinking:payload.thinking,imageDescriptions,metrics:apiResult.metrics,model:apiResult.model,createdAt:Date.now()};","if(!payload.reply&&!payload.voiceText)throw new Error('Model returned no visible reply');const assistantMessage={id:crypto.randomUUID(),requestId:requestId||undefined,role:'assistant',text:payload.reply||'',voiceText:payload.voiceText||'',thinking:payload.thinking,imageDescriptions,metrics:apiResult.metrics,model:apiResult.model,createdAt:Date.now()};");
source=source.replace("const imageText=Object.values(entry?.imageDescriptions||{}).filter(Boolean).join('；');return[entry?.text?.trim(),imageText?`图片内容：${imageText}`:''].filter(Boolean).join('\\n').slice(0,5000)","const imageText=Object.values(entry?.imageDescriptions||{}).filter(Boolean).join('；');return[entry?.text?.trim(),entry?.voiceText?.trim()?`语音：${entry.voiceText.trim()}`:'',imageText?`图片内容：${imageText}`:''].filter(Boolean).join('\\n').slice(0,5000)");
source=source.replace("const imageText=Object.values(entry.imageDescriptions||{}).filter(Boolean).join('；'),text=[entry.text?.trim(),imageText?`图片识别结果：${imageText}`:''].filter(Boolean).join('\\n');","const imageText=Object.values(entry.imageDescriptions||{}).filter(Boolean).join('；'),text=[entry.text?.trim(),entry.voiceText?.trim()?`[语音消息] ${entry.voiceText.trim()}`:'',imageText?`图片识别结果：${imageText}`:''].filter(Boolean).join('\\n');");
await writeFile(runtimePath,source,'utf8');
await import(pathToFileURL(runtimePath).href+`?v=${Date.now()}`);
